server:
  port: 8989
mongodb:
  primary:
    host: 192.168.157.101
    port: 27017
    database: test
  secondary:
    host: 192.168.157.101
    port: 27017
    database: test1
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
